# Generated by Django 4.0.3 on 2022-04-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='resourceavailability',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='resourcecost',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='resourceskilllevel',
            old_name='resource_skill_id',
            new_name='resource_skill',
        ),
        migrations.RenameField(
            model_name='resourceskilllevel',
            old_name='skill_level_id',
            new_name='skill_level',
        ),
        migrations.RenameField(
            model_name='resourceskills',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='resourceskills',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='resourcetimezone',
            old_name='resource_id',
            new_name='resource',
        ),
    ]
