# Generated by Django 4.0.3 on 2022-04-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_vendor_id_resource_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hours_per_day', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcecost',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceskilllevel',
            name='resource_skill',
        ),
        migrations.RemoveField(
            model_name='resourceskilllevel',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='resourceskills',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceskills',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='resourcetimezone',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='cost_per_hour',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='skills',
            field=models.ManyToManyField(to='resources.skill'),
        ),
        migrations.AddField(
            model_name='resource',
            name='time_zone',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.DeleteModel(
            name='ResourceAvailability',
        ),
        migrations.DeleteModel(
            name='ResourceCost',
        ),
        migrations.DeleteModel(
            name='ResourceSkillLevel',
        ),
        migrations.DeleteModel(
            name='ResourceSkills',
        ),
        migrations.DeleteModel(
            name='ResourceTimeZone',
        ),
        migrations.DeleteModel(
            name='SkillLevel',
        ),
        migrations.AddField(
            model_name='resource',
            name='availability',
            field=models.ManyToManyField(to='resources.availability'),
        ),
    ]
