# Generated by Django 4.0.3 on 2022-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_availability_remove_resourcecost_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='time_zone',
            field=models.CharField(default='cst', max_length=25),
        ),
    ]
