# Generated by Django 4.0.3 on 2022-05-10 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='availability',
        ),
        migrations.AddField(
            model_name='resource',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.availability'),
            preserve_default=False,
        ),
    ]
