# Generated by Django 4.0.3 on 2022-05-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resource_availability_resource_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='resource',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
            preserve_default=False,
        ),
    ]
